<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExperienceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $experiences = array(
            array('id' => '1', 'designation' => 'Software Engineer', 'duration' => 'May 2023 - Continue', 'company_name' => 'Adventure Dhaka Limited', 'company_address' => 'Banani, Dhaka, Bangladesh', 'work_description' => '<ul><li>• Leadership &amp; Team Collaboration : Lead and mentored a team of developers, fostering collaboration and productivity. Worked closely with cross-functional teams across different countries, ensuring alignment with project goals.</li><li>• Technology Adoption &amp; Innovation : Gained hands-on experience with cutting-edge technologies, including Docker for containerization, microservices architecture, system design, and unit testing, improving project efficiency and code quality.</li><li>• Large-Scale OTA Software Development : Played a pivotal role in developing and maintaining large-scale OTA (Online Travel Agency) software solutions, delivering high-performance, scalable, and reliable systems.</li><li>• International Collaboration : Collaborated with teams from multiple countries, enhancing communication and cultural adaptability while working on complex software projects.</li></ul>', 'sort_order' => '1', 'status' => 'active', 'created_at' => '2025-08-05 15:33:49', 'updated_at' => '2025-08-05 15:33:49'),
            array('id' => '2', 'designation' => 'Software Engineer', 'duration' => 'Aug 2021 - April 2023', 'company_name' => 'Arena Phone BD Limited', 'company_address' => 'Gulshan, Dhaka, Bangladesh', 'work_description' => '<p><span style="background-color: rgb(255, 255, 255); color: rgba(0, 0, 0, 0.9);">• Full-Stack Development : Gained hands-on experience in full-stack development, working on both the front-end and back-end of applications.</span></p><p><span style="background-color: rgb(255, 255, 255); color: rgba(0, 0, 0, 0.9);">• Quick Learning &amp; Support Skills : Demonstrated the ability to quickly learn new technologies and provide rapid technical support, ensuring smooth operations.</span></p><p><br></p><p><span style="background-color: rgb(255, 255, 255); color: rgba(0, 0, 0, 0.9);">Key Contributions :</span></p><p><span style="background-color: rgb(255, 255, 255); color: rgba(0, 0, 0, 0.9);"> • Developed a custom CMS and in-house accounting software to streamline internal operations.</span></p><p><span style="color: rgba(0, 0, 0, 0.9); background-color: rgb(255, 255, 255);"> • Played a significant role in projects like E-Sales, Vehicle Management, and School Management </span></p><p><span style="background-color: rgb(255, 255, 255); color: rgba(0, 0, 0, 0.9);"> Software.</span></p><p><br></p><p><span style="background-color: rgb(255, 255, 255); color: rgba(0, 0, 0, 0.9);">• Achievements : Promoted to Software Engineer, honed leadership skills, and contributed to large-scale projects while enhancing technical proficiency.</span></p>', 'sort_order' => '2', 'status' => 'active', 'created_at' => '2025-08-05 15:38:15', 'updated_at' => '2025-08-05 15:38:15'),
            array('id' => '3', 'designation' => 'Junior Software Engineer', 'duration' => 'Jan 2020 – Sep 2020', 'company_name' => 'Logic Software Limited', 'company_address' => 'Banani, Dhaka, Bangladesh', 'work_description' => '<p><span style="background-color: rgb(255, 255, 255); color: rgba(0, 0, 0, 0.9);">• Large Team Collaboration : Worked with a large, experienced team that included many senior developers, gaining valuable insights and mentorship.</span></p><p><span style="background-color: rgb(255, 255, 255); color: rgba(0, 0, 0, 0.9);">• Key Projects : Contributed to the development of Garment ERP and Accounting Software, delivering solutions for complex business needs.</span></p><p><br></p><p><span style="background-color: rgb(255, 255, 255); color: rgba(0, 0, 0, 0.9);">Skill Development</span></p><p><span style="background-color: rgb(255, 255, 255); color: rgba(0, 0, 0, 0.9);"> • Gained advanced debugging skills, improving the quality and performance of applications.</span></p><p><span style="background-color: rgb(255, 255, 255); color: rgba(0, 0, 0, 0.9);"> • Developed strong analytical skills, enhancing problem-solving capabilities in software development.</span></p><p><span style="background-color: rgb(255, 255, 255); color: rgba(0, 0, 0, 0.9);"> • Increased confidence by tackling challenging projects and collaborating with senior team members.</span></p>', 'sort_order' => '3', 'status' => 'active', 'created_at' => '2025-08-05 15:39:32', 'updated_at' => '2025-08-05 15:39:32')
        );
        DB::table('experiences')->insert($experiences);
    }
}
